# Generated by Django 5.2 on 2025-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_player',
            field=models.IntegerField(default=6),
        ),
    ]
