# Generated by Django 5.2 on 2025-07-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_max_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_time',
            field=models.IntegerField(default=20),
        ),
    ]
