# Generated by Django 5.2 on 2025-08-01 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_round_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
