# Generated by Django 5.2 on 2025-08-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='turn_order',
            field=models.JSONField(default=list),
        ),
    ]
