# Generated by Django 5.2 on 2025-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_hand_count_room_turn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_turn_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='turn_timer',
            field=models.IntegerField(default=30),
        ),
    ]
