# Generated by Django 5.2 on 2025-08-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_room_current_turn_index_room_turn_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turn_timer_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
